# Generated by Django 3.2.7 on 2022-01-18 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('cust_name', models.TextField()),
                ('password', models.TextField()),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.TextField()),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='flower',
            fields=[
                ('flower_id', models.IntegerField(primary_key=True, serialize=False)),
                ('flower_name', models.TextField()),
                ('color', models.CharField(max_length=60)),
                ('price', models.IntegerField()),
                ('flower_img', models.ImageField(upload_to='floral/static/img')),
            ],
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('purpose_id', models.IntegerField(primary_key=True, serialize=False)),
                ('flower_id', models.IntegerField()),
                ('name_of_service', models.TextField()),
                ('price', models.IntegerField()),
                ('flower_name', models.TextField()),
                ('services_img', models.ImageField(upload_to='floral/static/img')),
            ],
        ),
        migrations.CreateModel(
            name='uses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floral.customer')),
                ('purpose_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floral.services')),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flower_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floral.flower')),
                ('looksafter', models.ManyToManyField(to='floral.customer')),
            ],
        ),
        migrations.CreateModel(
            name='looksafters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floral.employee')),
                ('flower_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='floral.flower')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='looksafter',
            field=models.ManyToManyField(to='floral.flower'),
        ),
        migrations.AddField(
            model_name='customer',
            name='looksafter',
            field=models.ManyToManyField(to='floral.services'),
        ),
    ]
